package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VisiteurAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVisiteurAllPropertiesEquals(Visiteur expected, Visiteur actual) {
        assertVisiteurAutoGeneratedPropertiesEquals(expected, actual);
        assertVisiteurAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVisiteurAllUpdatablePropertiesEquals(Visiteur expected, Visiteur actual) {
        assertVisiteurUpdatableFieldsEquals(expected, actual);
        assertVisiteurUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVisiteurAutoGeneratedPropertiesEquals(Visiteur expected, Visiteur actual) {
        assertThat(actual)
            .as("Verify Visiteur auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVisiteurUpdatableFieldsEquals(Visiteur expected, Visiteur actual) {
        assertThat(actual)
            .as("Verify Visiteur relevant properties")
            .satisfies(a -> assertThat(a.getCv()).as("check cv").isEqualTo(expected.getCv()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVisiteurUpdatableRelationshipsEquals(Visiteur expected, Visiteur actual) {
        // empty method
    }
}
